# Generated by Django 3.0.5 on 2020-06-11 10:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('6b47e4aa-edb6-40fe-b04b-1e5e382ebb0b'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
