# Generated by Django 3.0.5 on 2020-06-11 10:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20200611_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4aabf956-9bc3-40b4-b8e6-88fff8ddf740'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
