# Generated by Django 3.0.5 on 2020-06-13 08:51

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20200611_1859'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='isbn',
            new_name='genre',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('de3bf24d-a982-4e17-aa95-13598fedce02'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
