# Generated by Django 3.0.5 on 2020-06-13 10:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20200613_1651'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('51930962-6f03-4a5d-85e4-7c05fa8b601f'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
