# Generated by Django 3.0.5 on 2020-06-14 06:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_auto_20200614_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('2ccea175-ba58-4655-ba7e-e7863b3c9648'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
