# Generated by Django 3.0.5 on 2020-06-14 07:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0007_auto_20200614_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('809b1206-b840-4a1e-820e-c788d12cbc3a'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
