# Generated by Django 3.0.5 on 2020-06-14 07:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0008_auto_20200614_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='language',
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f7609b72-4199-460c-848d-4dfd2633a479'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
