# Generated by Django 3.0.5 on 2020-06-16 10:38

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0010_auto_20200616_1630'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookinstance',
            options={'ordering': ['due_back'], 'permissions': (('can_mark_returned', 'Set book as returned'),)},
        ),
        migrations.AlterField(
            model_name='bookinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('3e35a77e-ebc8-4527-aeed-6a9943345425'), help_text='Unique ID for this particular book across whole library', primary_key=True, serialize=False),
        ),
    ]
